
# Oxia cluster configuration

oxia-cluster:
  enabled: true
  replicationFactor: 3
  initialShardCount: 6
  coordinator:
    cpu: "2"
    memory: 4Gi
  server:
    replicas: 6
    cpu: "2"
    memory: 8Gi
    storage: 128Gi
  pprofEnabled: true
  monitoringEnabled: true


# Zookeeper cluster configuration
zookeeper:
  enabled: false

# ETCD cluster configuration
etcd:
  enabled: false

# workers
workers:
  - name: oxia-worker
    parallelism: 12
    cpu: "2"
    memory: 4Gi
    driverConfig:
      driver: oxia
      config:
        serviceAddress: "benchmark-6:6648"
        batchMaxCount: 5000