
# Oxia cluster configuration

oxia-cluster:
  enabled: true
  replicationFactor: 3
  initialShardCount: 12
  coordinator:
    cpu: "2"
    memory: 4Gi
  server:
    replicas: 10
    cpu: "2"
    memory: 8Gi
    storage: 128Gi
  pprofEnabled: true
  monitoringEnabled: true



# Zookeeper cluster configuration
zookeeper:
  enabled: false

# ETCD cluster configuration
etcd:
  enabled: false

##  64 value
# workers
workers:
  - name: oxia-worker
    parallelism: 24
    cpu: "2"
    memory: 4Gi
    driverConfig:
      driver: oxia
      config:
        serviceAddress: "benchmark-12:6648"
        batchMaxCount: 5000